parameters:
    database_driver: pdo_mysql
    database_host: 192.186.219.66
    database_port: null
    database_name: HMvc
    database_user: pudel
    database_password: Kupa1234!
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f26f912d6139a1091e91fa4510a441e971
    database_path: /
